# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
rcppeigen_hello_world <- function() {
    .Call('_CARseq_rcppeigen_hello_world', PACKAGE = 'CARseq')
}

#' @export
rcppeigen_outerproduct <- function(x) {
    .Call('_CARseq_rcppeigen_outerproduct', PACKAGE = 'CARseq', x)
}

#' @export
rcppeigen_innerproduct <- function(x) {
    .Call('_CARseq_rcppeigen_innerproduct', PACKAGE = 'CARseq', x)
}

#' @export
rcppeigen_bothproducts <- function(x) {
    .Call('_CARseq_rcppeigen_bothproducts', PACKAGE = 'CARseq', x)
}

